# metrics
metric:
  mae:
    function: sklearn.metrics.mean_absolute_error
  mse:
    function: sklearn.metrics.mean_squared_error
  rmse:
    function: sklearn.metrics.root_mean_squared_error
  r2:
    function: sklearn.metrics.r2_score
    direction: maximize  # override default direction
# samplers for optuna
sampler:
  auto:
    class: "auto"
    params: {}
  tpe:
    class: optuna.samplers.TPESampler
    params:
      seed: 42
  random:
    class: optuna.samplers.RandomSampler
    params:
      seed: null
  cmaes:
    class: optuna.samplers.CmaEsSampler
    params:
      seed: null
# Training parameters (separate from model init)
training_params:
    learning_rate:
      type: 'float'
      low: 1.0e-4
      high: 1.0e-2
      log: true
    lr_reduce:
      type: 'float'
      low: 0.6
      high: 0.6
      log: false
# parameters for the GNN model
# parameters for the models
models:
  groupgat:
    class: 'src.grape.models.GroupGAT.GCGAT_v4pro'

    # Required parameters that will be inferred
    inferred_params:
      - name: 'node_in_dim'
        source: 'n_atom_features'
      - name: 'edge_in_dim'
        source: 'n_bond_features'

    # Fixed parameters
    fixed_params:
      out_channels: 1
      global_features: false

    # Parameters to optimize
    param_ranges:
      # Layer 1 parameters
      L1_hidden_dim:
        type: 'int'
        low: 64
        high: 256
        step: 32
      L1_layers_atom:
        type: 'int'
        low: 1
        high: 4
      L1_layers_mol:
        type: 'int'
        low: 1
        high: 4
      L1_out_dim:
        type: 'int'
        low: 32
        high: 128
        step: 16
      L1_dropout:
        type: 'float'
        low: 0.0
        high: 0.3

      # Layer 2 parameters
      L2_hidden_dim:
        type: 'int'
        low: 64
        high: 256
        step: 32
      L2_layers_atom:
        type: 'int'
        low: 1
        high: 4
      L2_layers_mol:
        type: 'int'
        low: 1
        high: 4
      L2_out_dim:
        type: 'int'
        low: 32
        high: 128
        step: 16
      L2_dropout:
        type: 'float'
        low: 0.0
        high: 0.3

      # Layer 3 parameters
      L3_hidden_dim:
        type: 'int'
        low: 32
        high: 128
        step: 32
      L3_layers_atom:
        type: 'int'
        low: 1
        high: 4
      L3_layers_mol:
        type: 'int'
        low: 1
        high: 4
      L3_out_dim:
        type: 'int'
        low: 32
        high: 128
        step: 16
      L3_dropout:
        type: 'float'
        low: 0.0
        high: 0.3

      # MLP and final parameters
      n_mlp_layers:
        type: 'int'
        low: 1
        high: 3
      mlp_dim:
        type: 'int'
        low: 16
        high: 64
        step: 8
      num_heads:
        type: 'int'
        low: 1
        high: 2
      final_dropout:
        type: 'float'
        low: 0.0
        high: 0.3

# set of default parameters
default_settings:
  direction: minimize
  n_trials: 5
  sampler: auto
  metric: rmse
  max_epochs: 150