# metrics
metric:
  mae:
    function: sklearn.metrics.mean_absolute_error
  mse:
    function: sklearn.metrics.mean_squared_error
  rmse:
    function: sklearn.metrics.root_mean_squared_error
  r2:
    function: sklearn.metrics.r2_score
    direction: maximize  # override default direction
# samplers for optuna
sampler:
  tpe:
    class: optuna.samplers.TPESampler
    params:
      seed: 10

  random:
    class: optuna.samplers.RandomSampler
    params:
      seed: 10

  cmaes:
    class: optuna.samplers.CmaEsSampler
    params:
      seed: 10

# model hyperparameters
models:
  svr:
    class: sklearn.svm.SVR
    param_ranges:
      kernel:
        type: categorical
        values: ['linear', 'rbf', 'poly']
      C:
        type: float
        low: 1e-1
        high: 1e3
        log: true
      gamma:
        type: float
        low: 1e-4
        high: 1e0
        log: true
      epsilon:
        type: float
        low: 0.0
        high: 0.3
        log: false
  rf:
    class: sklearn.ensemble.RandomForestRegressor
    param_ranges:
      n_estimators:
        type: int
        low: 10
        high: 500
        log: true
      max_depth:
        type: int
        low: 3
        high: 30
        log: false
      min_samples_split:
        type: int
        low: 2
        high: 20
        log: false

default_settings:
  direction: minimize
  n_trials: 50
  sampler: tpe
  metric: rmse